import turtle
import random
print('My project: https://scratch.mit.edu/projects/imnotgonnashowthisforpersonalreasons')
jeff = turtle.Turtle()
jeff.speed(0)
screen = turtle.Screen()
def delay(speed,fromx,fromy,tox,toy):
  jeff.penup()
  jeff.speed(speed)
  jeff.hideturtle()
  jeff.goto(tox,toy)
  jeff.goto(fromx,fromy)
  jeff.showturtle()
  jeff.speed(0)
def sun():
  print('Sun:')
  jeff.penup()
  jeff.color(255,215,0)
  jeff.goto(-200,200)
  jeff.pensize(100)
  jeff.pendown()
  jeff.fd(1)
  jeff.penup()
  jeff.goto(0,0)
def G_D():
  print('Grass and Dirt:')
  jeff.pensize(170)
  jeff.goto(-200,-200)
  jeff.color(128,66,66)
  jeff.pendown()
  jeff.forward(500)
  jeff.penup()
  jeff.pensize(20)
  jeff.color(3,181,0)
  jeff.goto(-250,-115)
  jeff.pendown()
  jeff.forward(500)
  jeff.penup()
  jeff.goto(0,0)
def flower():
  print('flower:')
  jeff.pensize(10)
  jeff.color(3,181,0)
  x = random.randint(-200,200)
  jeff.goto(x,-110)
  jeff.pendown()
  jeff.goto(x,-70)
  jeff.penup()
  c = random.randint(100,255)
  b = random.randint(200,255)
  a = random.randint(100,200)
  jeff.color(a,c,b)
  jeff.penup()
  jeff.pensize(30)
  jeff.pendown()
  jeff.forward(1)
  jeff.pensize(5)
  jeff.color(255,215,0)
  jeff.back(1)
  jeff.penup()
  jeff.goto(0,0)
def cloud():
  print('Cloud:')
  jeff.color('#e4e4e4')
  jeff.pensize(100)
  jeff.goto(-96,121)
  jeff.pendown()
  jeff.fd(1)
  jeff.penup()
  jeff.goto(-28,140)
  jeff.pendown()
  jeff.fd(1)
  jeff.penup()
  jeff.goto(50,114)
  jeff.pendown()
  jeff.back(140)
  jeff.penup()
  jeff.goto(0,0)
def thcloud():
  print('Thunder Cloud:')
  jeff.color('#a5a5a5')
  jeff.pensize(100)
  jeff.goto(-96,121)
  jeff.pendown()
  jeff.fd(1)
  jeff.penup()
  jeff.goto(-28,140)
  jeff.pendown()
  jeff.fd(1)
  jeff.penup()
  jeff.goto(50,114)
  jeff.pendown()
  jeff.bk(140)
  jeff.penup()
  jeff.goto(0,0)
def tree():
  print('Tree:')
  jeff.color('#804242')
  jeff.pensize(30)
  jeff.goto(0,-100)
  jeff.pendown()
  jeff.goto(0,0)
  jeff.color('#03b500')
  jeff.pensize(100)
  jeff.goto(0,30)
  jeff.penup()
def flowerat(posx):
  print('flower:')
  jeff.pensize(10)
  jeff.color(3,181,0)
  jeff.goto(posx,-110)
  jeff.pendown()
  jeff.goto(posx,-70)
  jeff.penup()
  c = random.randint(100,255)
  b = random.randint(200,255)
  a = random.randint(100,200)
  jeff.color(a,c,b)
  jeff.penup()
  jeff.pensize(30)
  jeff.pendown()
  jeff.forward(1)
  jeff.pensize(5)
  jeff.color(255,215,0)
  jeff.back(1)
  jeff.penup()
  jeff.goto(0,0)
def landscape():
  jeff.penup()
  cloud()
  tree()
  flowerat(-100)
  flowerat(100)
  G_D()
def clear():
  jeff.clear()
jeff.penup()
print('''
Sun: "a"
Grass and Dirt: "b"
Flower: "c"
Cloud: "d"
Tunder Cloud: "e"
Tree: "f"
Clear: space

Oh, and if you hold down keys, it gets really glitchy.''')
screen.onkey(sun, 'a')
screen.onkey(G_D, 'b')
screen.onkey(flower, 'c')
screen.onkey(cloud, 'd')
screen.onkey(thcloud, 'e')
screen.onkey(tree, 'f')
screen.onkey(clear, ' ')
screen.listen()
